language: php

php:
  - 5.6
  - 7.0
  - 7.1
  # Use the newer stack for HHVM as HHVM does not support Precise
  #- php: hhvm
  #  sudo: required
  #  dist: trusty
  #  group: edge

before_install:
- composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
- composer install --dev
 
script:
- mkdir -p build/logs && ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
 
after_script:
- php vendor/bin/coveralls -v
