language: php

php:
  - 5.6
  - 7

before_install:
- composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
- composer install --dev
 
script:
- mkdir -p build/logs && ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
 
after_script:
- php vendor/bin/coveralls -v
